version: "3"

services:
  backend:
    container_name: spring
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
    ports:
    - "8080:8080"
    depends_on:
      - db

  db:
    container_name: post
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-solomid123}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
    - "5432:5432"
  front:
    build: ../sayeb
    container_name: frontend
    ports:
      - "4200:80"
    links:
      - backend



volumes:
 postgres:

